name: Create pull-request
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  pull-request-required-checks:
    name: Linting code
    runs-on: ubuntu-latest
    steps:
      - name: linting
        run: |
          echo "Check is OK"