name: Create pull-request
on:
  pull_request:
    types:
      - opened
      #- reopened
      #- synchronize
      #- labeled
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  pull-request-required-checks:
    name: Pull request required checks
    runs-on: ubuntu-latest
    steps:
      - name: check 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number $GITHUB_EVENT_PATH)
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/check-runs \
          -d @- << EOF
          {
            "name": "My Check 1",
            "head_sha": "${{ github.event.pull_request.head.sha }}",
            "status": "queued",
            "output": {
              "title": "My Check 1 Title",
              "summary": "This is a custom check that needs to pass before merging."
            }
          }
          EOF

      - name: check 2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number $GITHUB_EVENT_PATH)
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/check-runs \
          -d @- << EOF
          {
            "name": "My Check 2",
            "head_sha": "${{ github.event.pull_request.head.sha }}",
            "status": "queued",
            "output": {
              "title": "My Check 2 Title",
              "summary": "This is a custom check that needs to pass before merging."
            }
          }
          EOF