name: Create pull-request
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  auto-pass:
    if: github.actor == 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Set PR  check to success
        run: |
          PR_SHA=$(jq -r .pull_request.head.sha "$GITHUB_EVENT_PATH")
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -X POST \
               -d '{"state":"success", "context":"linting"}' \
               https://api.github.com/repos/${{ github.repository }}/statuses/$PR_SHA

  pr-checks:
    name: Pull request required checks
    runs-on: ubuntu-latest
    steps:
      - name: check 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number $GITHUB_EVENT_PATH)
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/check-runs \
          -d @- << EOF
          {
            "name": "My Check",
            "head_sha": "${{ github.event.pull_request.head.sha }}",
            "status": "in_progress",
            "output": {
              "title": "My Check Title",
              "summary": "This is a custom check that needs to pass before merging.",
              "text": "Detailed information about the check."
            }
          }
          EOF
      - name: check 2
        run: |
          echo "PR check 2"
