name: Create pull-request
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  auto-pass:
    if: github.actor == 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Set PR  check to success
        run: |
          PR_SHA=$(jq -r .pull_request.head.sha "$GITHUB_EVENT_PATH")
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -X POST \
               -d '{"state":"success", "context":"linting"}' \
               https://api.github.com/repos/${{ github.repository }}/statuses/$PR_SHA

  pr-checks:
    name: Pull request required checks
    runs-on: ubuntu-latest
    steps:
      - name: check 1
        run: |
          echo "PR check 1"
      - name: check 2
        run: |
          echo "PR check 2"
