name: Release version
on:
  push:
    branches:
      - main

jobs:
  release-please:
    uses: ./.github/workflows/release-please.yaml
    secrets: inherit

  build:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created == 'true' }}
    steps:
      - name:
        run: |
          echo "sestaveni kontejneru"

