name: Release version
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release_please:
    uses: ./.github/workflows/release-please.yaml
    secrets: inherit

  build:
    runs-on: ubuntu-latest
    needs: release_please
    if: ${{ needs.release_please.outputs.release_created == 'true' }}
    steps:
      - name:
        run: |
          echo "sestaveni kontejneru"

